[package]
name = "tree-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
accumulators = { version = "0.4", features = ["all"] }
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"
hex = "0.4"

[dev-dependencies]
hex = "0.4"
